server:
  port: 9090

spring:
  application:
    name: CloudGateway

  config:
    import: configserver:http://localhost:9296

  cloud:
    gateway:
      routes:
        - id: ORDER-SERVICE
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order/**
          filters:
            - name: CircuitBreaker
              args:
                name: ORDER-SERVICE
                fallbackuri: forward:/orderServiceFallBack


        - id: PRODUCT-SERVCIE
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/product/**
          filters:
            - name: CircuitBreaker
              args:
                name: PRODUCT-SERVICE
                fallbackuri: forward:/productServiceFallback

        - id: PAYMENT-SERVICE
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payment/**
          filters:
            - name: CircuitBreaker
              args:
                name: PAYMENT-SERVICE
                fallbackuri: forward:/paymentServiceFallback

okta:
  oauth2:
    issuer: https://dev-41763453.okta.com/oauth2/default
    audience: api://default
    client-id: 0oagew24a91kPdCov5d7
    client-secret: 4izJqi3EtP05xxnaEBF2sS_vYA_oRSDFQTVtQ_iQHT09xJQjKdzuzaMe2ORlM-FC
    scopes: openid, profile, email, offline_access


#<!-- Either create a Customizer Bean or use below config for resilience4j -->
#resilience4j:
#  circuitbreaker:
#    instances:
#      CircuitBreaker:
#        eventConsumerBufferSize: 10
#        failureRateThreshold: 50
#        minimumNumberOfCalls: 5
#        automaticTransitionFromOpenToHalfOpenEnabled: true
#        waitDurationInOpenState: 5s
#        permittedNumberOfCallsInHalfOpenState: 3
#        slidingWindowSize: 10
#        slidingWindowType: COUNT_BASED
