server:
  port: 9090

spring:
  application:
    name: CloudGateway

  config:
    import: configserver:http://localhost:9296

  cloud:
    gateway:
      routes:
        - id: ORDER-SERVICE
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order/**

        - id: PRODUCT-SERVCIE
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/product/**

        - id: PAYMENT-SERVICE
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payment/**
